// collection_mapping.js

// 1. Main collection IDs for special rules
export const COLLECTION_IDS = {
    BEADS: 'gid://shopify/Collection/1234567890',
    ROUND_POLISHED: 'gid://shopify/Collection/2345678901',
    ROUND_FACETED: 'gid://shopify/Collection/3456789012',
    ROUND_FROSTED: 'gid://shopify/Collection/4567890123',
    RONDELLE_FACETED: 'gid://shopify/Collection/6789012345',
    RONDELLE_FROSTED: 'gid://shopify/Collection/7890123456',
    RONDELLE_POLISHED: 'gid://shopify/Collection/5678901234',
    SPACE_SHIP: "286925914202",
    PEAR: 'gid://shopify/Collection/0123456789',
    SQUARE: "286925717594",
    BARREL: "286925815898",
    HEART: 'gid://shopify/Collection/7890123456',
    BLADE: "286925684826",
    FREEFORM: 'gid://shopify/Collection/8901234567'
};

// 2. Freeform shapes
export const FREEFORM_SHAPES = [
    'FREEFORM',
    'ROUGH',
    'NATURAL',
    'ORGANIC'
];

// 3. Shape collections
export const SHAPE_COLLECTIONS = {
    'OVAL': 'gid://shopify/Collection/9012345678',
    'PEAR': 'gid://shopify/Collection/0123456789',
    'SQUARE': "286925717594",
    'BARREL': "286925815898",
    'HEART': 'gid://shopify/Collection/7890123456',
    'BLADE': "286925684826"
};

// 4. Stone name mapping with aliases
export const stoneAliases = {
    'RUBY': ['RUBY', 'RUBIES'],
    'SAPPHIRE': ['SAPPHIRE', 'SAPPHIRES'],
    'EMERALD': ['EMERALD', 'EMERALDS'],
    'DIAMOND': ['DIAMOND', 'DIAMONDS'],
    'AMETHYST': ['AMETHYST', 'AMETHYSTS'],
    'CITRINE': ['CITRINE', 'CITRINES'],
    'TOPAZ': ['TOPAZ', 'TOPAZES'],
    'GARNET': ['GARNET', 'GARNETS'],
    'PERIDOT': ['PERIDOT', 'PERIDOTS'],
    'AQUAMARINE': ['AQUAMARINE', 'AQUAMARINES'],
    "AGATE": ["AGATE"],
    "APATITE": ["APATITE"],
    "JASPER": ["JASPER"],
    "BLOODSTONE": ["BLOODSTONE", "DRAGON'S BLOOD", "DRAGONS BLOOD", "BLOSSOM"],
    "ONYX": ["ONYX"],
    "QUARTZ": ["QUARTZ"],
    "CORAL": ["CORAL"],
    "RHODONITE": ["RHODONITE"],
    "AMETHYST": ["AMETHYST"],
    "HAWK'S EYE": ["HAWK'S EYE"],
    "DUMORTIERITE": ["DUMORTIERITE"],
    "AQUAMARINE": ["AQUAMARINE"],
    "OPAL": ["OPAL", "OPALITE"],
    "JADE": ["JADE"],
    "SERPENTINE": ["SERPENTINE"],
    "SHELL": ["SHELL"],
    "MOOKAITE": ["MOOKAITE"],
    "TIGER'S EYE": ["TIGER'S EYE", "TIGERS EYE", "TIGER IRON"],
    "CALCITE": ["CALCITE"],
    "FLUORITE": ["FLUORITE"],
    "MORION": ["MORION"],
    "MARBLE": ["MARBLE"],
    "RIVER ROCK": ["RIVER ROCK"],
    "PETRIFIED WOOD": ["PETRIFIED WOOD"],
    "PHOENIX": ["PHOENIX"],
    "GARNET": ["GARNET", "PYROPE"],
    "TOURMALINE": ["TOURMALINE", "TOURMALINATED"],
    "LABRADORITE": ["LABRADORITE"],
    "AMAZONITE": ["AMAZONITE"],
    "MOONSTONE": ["MOONSTONE"],
    "CITRINE": ["CITRINE"],
    "TURQUOISE": ["TURQUOISE"],
    "LAPIS LAZULI": ["LAPIS LAZULI"],
    "SUNSTONE": ["SUNSTONE"],
    "RUBY": ["RUBY"],
    "SODALITE": ["SODALITE"],
    "IOLITE": ["IOLITE"],
    "OBSIDIAN": ["OBSIDIAN"],
    "AZURITE": ["AZURITE"],
    "CHRYSOCOLLA": ["CHRYSOCOLLA"],
    "SPINEL": ["SPINEL"],
    "LARIMAR": ["LARIMAR"],
    "PREHNITE": ["PREHNITE"],
    "MORGANITE": ["MORGANITE"],
    "CHRYSOPRASE": ["CHRYSOPRASE"],
    "MOTHER OF PEARL": ["MOTHER OF PEARL", "PEARLS"],
    "CHALCEDONY": ["CHALCEDONY"],
    "DIOPSIDE": ["DIOPSIDE"],
    "LEPIDOLITE": ["LEPIDOLITE"],
    "PERIDOT": ["PERIDOT"],
    "SAPPHIRE": ["SAPPHIRE"],
    "GLACIER": ["GLACIER"],
    "KYANITE": ["KYANITE"],
    "CARNELIAN": ["CARNELIAN"],
    "RHODOCHROSITE": ["RHODOCHROSITE", "RHODOCROSITE"],
    "KUNZITE": ["KUNZITE"],
    "LAVENDER": ["LAVENDER"],
    "MALACHITE": ["MALACHITE"],
    "TANZANITE": ["TANZANITE"],
    "AMETRINE": ["AMETRINE"],
    "LAVA": ["LAVA"],
    "MICA": ["MICA"],
    "CHAKRA": ["CHAKRA"],
    "CHAROITE": ["CHAROITE"],
    "UNAKITE": ["UNAKITE"],
    "FUCHSITE": ["FUCHSITE"],
    "HOWLITE": ["HOWLITE"],
    "LARVIKITE": ["LARVIKITE"],
    "LODALITE": ["LODALITE"],
    "PYRITE": ["PYRITE"],
    "RHODOLITE": ["RHODOLITE"],
    "SERAPHINITE": ["SERAPHINITE"],
    "SUGILITE": ["SUGILITE"],
    "TERAHERTZ": ["TERAHERTZ"],
    "ANGELITE": ["ANGELITE"],
    "BOULDER": ["BOULDER"],
    "CALLIGRAPHY": ["CALLIGRAPHY"],
    "LIANITE": ["LIANITE"],
    "PIETERSITE": ["PIETERSITE"],
    "SHATTUCKITE": ["SHATTUCKITE"],
    "SHUNGITE": ["SHUNGITE"],
    "SMITHSONITE": ["SMITHSONITE"],
    "ARFVEDSONITE": ["ARFVEDSONITE"],
    "ARUSHA": ["ARUSHA"],
    "FELDSPAR": ["FELDSPAR"],
    "BIOTITE": ["BIOTITE"],
    "BLACK SILVER LEAF": ["BLACK SILVER LEAF"],
    "SANDSTONE": ["SANDSTONE"],
    "BRONZITE": ["BRONZITE"],
    "CHAMPAGNE": ["CHAMPAGNE"],
    "EPIDOTE": ["EPIDOTE"],
    "AQUAPRASE": ["AQUAPRASE"],
    "PHOSPHOSIDERITE": ["PHOSPHOSIDERITE", "PHOSPHOSEDORITE"],
    "PHANTOM": ["PHANTOM"],
    "HYPERSTENE": ["HYPERSTENE", "HYPERSTINE"],
    "MANGANO": ["MANGANO"],
    "MERLINITE": ["MERLINITE"],
    "CELESTITE": ["CELESTITE"],
    "TROLLEITE": ["TROLLEITE"],
    "OOLITE": ["OOLITE"],
    "PHOSPHORITE": ["PHOSPHORITE"],
    "SELENITE": ["SELENITE"],
    "STICHTITE": ["STICHTITE"],
    "THULITE": ["THULITE"],
    "VARISCITE": ["VARISCITE"],
    "YOOPERLITE": ["YOOPERLITE"],
    "HEMATOID": ["HEMATOID"],
    "HEMIMORPHITE": ["HEMIMORPHITE"],
    "K2": ["K2"],
    "HEMATITE": ["HEMATITE"],
    "JET": ["JET"],
    "TIFFANY STONE": ["TIFFANY STONE", "TIFFANY"],
    "GOLDEN HEALER": ["GOLDEN HEALER"],
    "MIXED": ["MIXED"],
    "ZOISITE": ["ZOISITE"],
    "CAT'S EYE": ["CAT'S EYE", "CATS EYE"],
    "APACHE": ["APACHE"]
};

// 5. Helper to build gemstone name → collection ID map from your collections JSON
export function buildGemstoneCollectionMap(collections) {
    const map = {};
    for (const collection of collections) {
        if (collection.title.includes('STONE')) {
            const stoneName = collection.title.split(' ')[0];
            map[stoneName] = collection.id;
        }
    }
    return map;
}